url: https://jordan-codemotive.github.io
baseurl:

# Site settings
title: codemotive
email: jordan@codemotive.co.uk
description: "Welcome to codemotive, a leading provider of custom software development solutions using .NET. With 12 years of experience in the industry, we have a track record of delivering high-quality software solutions to clients in a variety of industries. Our process is collaborative, and we work closely with our clients to understand their unique needs and challenges."

# Team names, titles and social links
people:
  - name: Jordan Beard
    pic: jordan
    position: Lead Software Developer
    social:
      - title: github
        url: https://github.com/jordan-codemotive
      - title: linkedin
        url: https://www.linkedin.com/in/beardjordan/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
